Pipeline(steps=[('maxabsscaler', MaxAbsScaler()),
                ('selectfrommodel',
                 SelectFromModel(estimator=ExtraTreesRegressor(bootstrap=True,
                                                               max_features=0.6461855611182,
                                                               min_samples_leaf=8,
                                                               min_samples_split=16,
                                                               n_jobs=1,
                                                               random_state=42),
                                 threshold=0.0084536361245)),
                ('featureunion-1',
                 FeatureUnion(transformer_list=[('skiptransformer',
                                                 SkipTransformer()),
                                                ('passthrough',
                                                 Passthrough())])),
                ('featureunion-2',
                 FeatureUnion(transformer_list=[('skiptransformer',
                                                 SkipTransformer()),
                                                ('passthrough',
                                                 Passthrough())])),
                ('lgbmregressor',
                 LGBMRegressor(boosting_type='goss', max_depth=9,
                               n_estimators=36, n_jobs=1, num_leaves=94,
                               random_state=42, verbose=-1))])